###
GET  https://mynodeapp.cfapps.us10-001.hana.ondemand.com HTTP/1.1

###
GET https://mynodeapp.cfapps.us10-001.hana.ondemand.com/AllProducts HTTP/1.1

###
POST https://mynodeapp.cfapps.us10-001.hana.ondemand.com/AllProducts HTTP/1.1
Content-Type: application/json

{
            "ProductID": 7,
            "ProductName": "Chai",
            "SupplierID": 1,
            "CategoryID": 1,
            "QuantityPerUnit": "10 boxes x 20 bags",
            "UnitPrice": "18.0000",
            "UnitsInStock": 39,
            "UnitsOnOrder": 0,
            "ReorderLevel": 10,
            "Discontinued": false
}

### call external Northwind service
GET https://mynodeapp.cfapps.us10-001.hana.ondemand.com/api/v1/Northwind_srv HTTP/1.1

### call external Northwind service with $filter
GET https://mynodeapp.cfapps.us10-001.hana.ondemand.com/api/v1/Northwind_srv/Products/SupplierID=2 HTTP/1.1